### ISSUE TITLE
Comment causes function detection to fail

### ISSUE THREAD

**Issue by makeitsquare** [gillibrand/expand-selection-to-function-js#6]
If the function has a comment between the closing round bracket for the arguments and the opening curly bracket for the body, the detection fails:

Example:
function doesNotWork() // example of a function that is NOT detected
{
     println("hello");
}

function doesWork() { // example of a function that is detected
     println("hello");
}

**Comment by gillibrand** [comment]
Here's a fix for this, but it's been so long since I've updated touched this, I can't remember how updates work. This package uses the older way, but I think is still supported. If it won't update, remove and reinstalling should work.

This is a simple fix that just iterates until it finds the opening brace.

**Comment by gillibrand** [comment]
Added versioned releases so that this package _should_ auto update from now on.

**Comment by makeitsquare** [comment]
Thanks for the quick fix. Update from within Sublime worked!
